<template>
  <section class="w-full flex bg-white dark:bg-[#161616] py-5 md:py-28  font-Inter relative">
    <div class="m-auto w-full max-w-[1150px] p-6">
      <div class="w-full flex flex-col items-center space-y-14">
        <span class="font-Inter font-semibold text-[#1B2C42] dark:text-white text-2xl md:text-5xl"
          >Privacy policy</span
        >
<div class="">
    <p class="normaltext">
                                        <p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Protecting your personal information is an important priority for Wallex. This privacy policy is designed to support this objective and, where applicable, sets out how Wallex will process personal information as a Data Controller. Wallex collects non-public personal information provided by you or your representative on applications or other forms furnished to Wallex or through other interactions that you or your representative have with Wallex. We urge you to read this Privacy Policy carefully as it contains important information on who we are, how and why we collect, store, use, and share personal information and on how to contact Wallex and supervisory authorities in the event you have a complaint. This Privacy Policy applies to websites owned and operated by Wallex and as well as all services provided by Wallex.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Wallex does not disclose any non-public personal information about you, except as permitted by law. If you decide to close your account, Wallex will continue to adhere to the privacy policies and practices as described in this notice.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">How and Why We Obtain Information</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Wallex may receive non-public personal information about you (the &ldquo;Personal Information&rdquo;) from any of the following sources: Your applications or forms (for example, name, address, Social Security number, birth date, assets, and income); Transactional activity in your account (for example, trading history and balances); Information from consumer reporting agencies; Information from other third-party data services (for example, to verify your identity and to better understand your product and service needs); Other sources with your consent or with the consent of your broker;</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Wallex may process the Personal Information for the following purposes:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Managing and administrating any account you may hold with Wallex on an ongoing basis (the &ldquo;Services&rdquo;);</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Wallex will itself (or through a third party e.g. credit reference agency) process certain information about you or your directors, officers and employees, and your beneficial owners (if applicable) in order to carry out anti-money laundering (AML) checks and related actions which Wallex considers appropriate to meet any legal obligations imposed on Wallex relating to, or the processing in the public interest or to pursue Wallex&rsquo;s legitimate interests in relation to, the prevention of fraud, money laundering, terrorist financing, bribery, corruption, tax evasion and to prevent the provision of financial and other services to persons who may be subject to economic or trade sanctions, on an on-going basis, in accordance with Wallex&lsquo;s AML procedures;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to report tax-related information to tax authorities in order to comply with a legal obligation;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to monitor and record calls and electronic communications for investigation and fraud prevention purposes, for crime detection, prevention, investigation, and prosecution, and to enforce or defend to report tax-related information to tax authorities in order to comply with a legal obligation;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to monitor and record calls and electronic communications for investigation and fraud prevention purposes, for crime detection, prevention, investigation, and prosecution, and to enforce or defend Wallex and its affiliates&rsquo; rights, itself or through third parties to whom it delegates such responsibilities or rights in order to comply with a legal obligation imposed on Wallex or to pursue Wallex&rsquo;s legitimate interests in relation to such matters or the processing in the public interest;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to monitor and record calls for quality, business analysis, training, and related purposes in order to pursue the legitimate interests of Wallex to improve its service delivery;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to update and maintain records and for fee billing;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to carry out statistical analysis and market research;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to provide you with information about products and services which may be of interest to you or to the institution you represent, and which processing is necessary to perform a relevant contract with you, comply with legal obligations, and/or which is necessary for Wallex&rsquo;s legitimate interests indicated above and/or where the processing is in the public interest; and</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">to retain AML and other records of individuals to assist with the subsequent screening of them, including in relation to investment in other funds or the provision of other services by Wallex, to pursue Wallex&rsquo;s and (in some circumstances) its clients&rsquo; legitimate interests.</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">How We Protect Information About You</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">We take reasonable security measures consistent with applicable law to protect the security of your Personal Information from being accidentally lost, or used, or accessed in an unauthorized way. We limit access to your personal information to those who have a genuine business need to know it.Those processing your information will do so only in an authorized manner and are subject to a duty of confidentiality. We also have procedures in place to deal with any suspected data security breach. We will notify you and any applicable regulator of a suspected data security breach where we are legally required to do so. We also implement the use of encryption or Secure Socket Layers connections for the transmission of any Personal Information. In so much as personal email is generally not encrypted, we request that no Personal Information be sent to us via email.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">We will retain your Personal Information as long as an account is active or as needed to provide you ervices. You may, at any time, instruct us to remove Personal Information, but you should be aware that it is not technologically possible to remove each and every record of the information you have provided to Wallex from our servers. We will also retain your Personal Information as necessary to comply with legal obligations, resolve disputes and enforce our agreements.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">User preferences and opt-out choices</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><em><span style="font-family: Inter,sans-serif;">Email, Direct Mail, Telemarketing, and Third-Party Sharing.</span></em></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">To opt out of:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Receiving promotional or marketing emails from Wallex at a specific email address;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Receiving direct mail;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Receiving calls;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Receiving notifications provided as part of the Services;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Disclosure of your information to third-parties; and</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Use of your information for a purpose that is materially different from the purpose(s) for which it was originally collected or subsequently authorized.</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">How We Share Information About You</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">We may share the personal information that we collect about our customers, prospects, or former customers with their brokers or with:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Wallex corporate affiliates, including internal service providers;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Unaffiliated service providers (for example, printing and mailing companies, liquidity providers, and other entities who may provide services at Wallex&rsquo;s direction)</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Government agencies, other regulatory bodies, and law enforcement officials (for example, for tax purposes or for reporting suspicious transactions)</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">To credit reference agencies in order to carry out money laundering and identity checks and comply with legal obligations;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">To Wallex affiliates and third-party vendors in order to process the data for legitimate purposes;</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Other organizations, with your consent or as directed by your broker (for example, if you request personalized performance reporting) or as permitted or required by law (for example, for fraud prevention or to respond to a subpoena)</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">To competent authorities, courts, and bodies as required by law or requested or to affiliated for internal investigations and reporting.The disclosure of personal information to the affiliates and other third parties set out above may involve the transfer of data to the USA and other jurisdictions outside the European Economic Area (EEA). Such countries may not have the same data protection laws as your jurisdiction. Wallex has put in place the Standard Contractual Clauses approved by the European Union Commission for such transfers of personal data. Please contact admin@wallexbank.com should you require more information on Wallex&rsquo;s international data transfer solution. Our service providers are obligated to keep the personal information we share with them confidential and use it only to provide services specified by Wallex.</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">Online Privacy</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Privacy, security, and service in Wallex&rsquo;s online operations are just as critical as in the rest of our business. We use firewall barriers, encryption techniques, and authentication procedures, among others, to maintain the security of your online session and to protect Wallex accounts and systems from unauthorized access.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">When you interact with us through online channels (for example, websites and mobile applications) owned and controlled by Wallex (&ldquo;Wallex websites&rdquo;), Wallex manages personal information in accordance with all of the practices and safeguards described previously.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">When you visit Wallex&rsquo;s websites, we may collect technical and navigational information, such as device type, browser type, Internet protocol address, pages visited, and average time spent on Wallex&rsquo;s websites. We use this information for a variety of purposes, such as maintaining the security of your online session, facilitating site navigation, improving Wallex&rsquo;s website design and functionality, and personalizing your experience on Wallex&rsquo;s websites. Additionally, the following policies and practices apply when you are online: Wallex provides information to its clients through electronic means only. These include Email, website, and online platform. Kindly note that to receive information electronically from Wallex, a valid Email address is required. Wallex provides information through our website which may not be addressed personally to you.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;" id="cookies">Cookies and similar technologies</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">We use cookies and similar technologies to support the operation of Wallex websites. Cookies are small amounts of data that website exchanges with a web browser or application on a visitor&rsquo;s computer or mobile device.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Cookies help us to collect information about visitors to Wallex websites, including date and time of visits, pages viewed, amount of time spent on our sites, or general information about the device used to access the site. Wallex cookies are also used for security purposes and to personalize your experience, such as customizing your screen layout.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">You can refuse or delete cookies. Most browsers and mobile devices offer their own settings to manage cookies. If you refuse a cookie when on an Wallex website, or if you delete cookies, you may experience some inconvenience in your use of Wallex websites. For example, you may not be able to sign in and access your account, or we may not be able to recognize you, your device, or your online preferences.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">Connecting with Wallex</span></strong><strong><span style="font-family: Inter,sans-serif;">&nbsp;</span></strong><strong><span style="font-family: Inter,sans-serif;">on social media sites</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Wallex provides experiences on social media platforms that enable online sharing and collaboration among users who have registered to use them. We may collect the information you provide by interacting with us via social media, such as photographs, opinions, or Twitter handle. Any content you post, such as pictures, information, opinions, or any personal information that you make available to other participants on these social platforms, is also subject to the Terms of Use and Privacy Policies of those platforms. Please refer to them to better understand your rights and obligations with regard to such content.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">Wallex mobile applications</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Wallex mobile applications (&ldquo;apps&rdquo;) allow you to access your accounts, trade securities, move money, and access third-party news and research using wireless or mobile devices. Our privacy practices apply to any personal information or other information that we may collect through the apps.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">Protecting children&rsquo;s privacy online</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Wallex websites are not directed to individuals under the age of thirteen (13). Wallex does not intentionally collect information on Wallex websites from those we actually know are under 13, and we request that these individuals do not provide personal information through the sites.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">Access to Your Information</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">You may access and, if necessary, correct your account information through a variety of media offered by your broker and Wallex(e.g., statements or online services). Please contact your broker if you require any additional information.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Data Subject Rights You have the following rights, in certain circumstances, in relation to your personal information:</span></p>
<ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Right to access your personal information.</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Right to rectify your personal information.</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Right to restrict the use of your personal information.</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Right to request that your personal information is erased.</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Right to object to processing of your personal information.</span></li>
    <li style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;vertical-align:baseline;'><span style="font-family: Inter,sans-serif;">Right to data portability (in certain specific circumstances).</span></li>
</ul>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">Where you have provided your consent to processing (e.g. to receive information about products and services which may be of interest to you or to the institution you represent), you may withdraw your consent at any time by contacting Wallex by email at admin@wallexbank.com Where Wallex requires your personal information to comply with AML or other legal requirements, failure to provide this information means Wallex may not be able to provide the Services or the service to the institution you represent. You have the right to lodge a complaint with a supervisory authority.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">Additional Information</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">If you are a former customer, your information is treated in the same manner as the information of current customers.Wallexoffers several options for accessing and, if necessary, correcting your account information. You can review your information using your statements, or through our automated telephone or Internet services. You may also write or call us with your request for information. If we serve you through an affiliate, please contact them directly.</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><strong><span style="font-family: Inter,sans-serif;">How To Complain</span></strong></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;line-height:24.0pt;'><span style="font-family: Inter,sans-serif;">We hope that we can resolve any query or concern you raise about our use of your information. Those in Designated Countries (being the European Union, European Economic Area or Switzerland) may contact our Privacy</span></p>
<p style='margin:0cm;font-size:16px;font-family: Inter,sans-serif;'>&nbsp;</p>
                                    </p>
      </div>
      </div>
    </div>
  </section>
</template>




